---
title: "Lab06"
author: "Mateus Bortolucci"
format: typst
editor: visual
---
```{r}
path <- getwd()
fname <- file.path(path, "disco.db")
```

```{r}
library(DBI)
library(RSQLite)
conn <- dbConnect(RSQLite::SQLite(), fname)
```

```{r}
tabelas <- dbListTables(conn)
tabelas
```

```{r}
colunas_custumers <- dbListFields(conn, "customers")
colunas_custumers 
```
```{r}
colunas_tracks <- dbListFields(conn, "tracks")
colunas_tracks
```


```{sql connection=conn}
SELECT COUNT(CustomerId) FROM customers
```
```{sql connection=conn}
SELECT COUNT(DISTINCT Country) FROM customers
```
```{sql connection=conn}
SELECT COUNTRY, COUNT(CustomerId) FROM CUSTOMERS
GROUP BY COUNTRY
ORDER BY COUNT(CustomerId) DESC
```

```{sql connection=conn}
SELECT COUNTRY FROM CUSTOMERS
GROUP BY COUNTRY
ORDER BY COUNT(COUNTRY) DESC
LIMIT 5
```


```{sql connection=conn}
SELECT DISTINCT COUNTRY FROM CUSTOMERS
WHERE COUNTRY LIKE "______"
```

```{sql connection=conn}
SELECT DISTINCT t.Name 
FROM tracks t
INNER JOIN invoice_items ii ON t.TrackId = ii.TrackId
INNER JOIN invoices i ON ii.InvoiceId = i.InvoiceId
INNER JOIN customers c ON i.CustomerId = c.CustomerId
WHERE Country = 'Brazil'
ORDER BY Name;
```

```{r}
dbDisconnect(conn)
```



```{r}
Sys.setenv(TZ = "America/Sao_Paulo")
Sys.time()
```

